export const PRODUCTS = [
  { id: "u1", slug: "cloudrun-prime-knit", name: "CloudRun Prime Knit", price: 129.99, gender: "Men", category: "Shoes", colors: ["Black","White","Core Blue"], sizes: [7,8,9,10,11,12], rating: 4.7, tags: ["new","bestseller"], img: "https://picsum.photos/seed/cloudrun1/1200/900", images: ["https://picsum.photos/seed/cloudrun1/1200/900","https://picsum.photos/seed/cloudrun1b/1200/900","https://picsum.photos/seed/cloudrun1c/1200/900"], description: "Breathable knit upper with responsive foam for daily training.", specs: { weight: "260 g", drop: "8 mm", upper: "Knit" } },
  { id: "u2", slug: "aeroflex-training-tee", name: "AeroFlex Training Tee", price: 35, gender: "Men", category: "Apparel", colors: ["White","Black","Volt"], sizes: ["S","M","L","XL"], rating: 4.4, tags: ["new"], img: "https://picsum.photos/seed/tee2/1200/900", images: ["https://picsum.photos/seed/tee2/1200/900"], description: "Ultra-light tee that wicks and dries fast.", specs: { material: "Poly blend" } },
  { id: "u3", slug: "stride-5-shorts", name: "Stride 5 Shorts", price: 42, gender: "Women", category: "Apparel", colors: ["Pink","Black"], sizes: ["XS","S","M","L"], rating: 4.6, tags: ["bestseller"], img: "https://picsum.photos/seed/shorts3/1200/900", images: ["https://picsum.photos/seed/shorts3/1200/900"], description: "Featherweight running shorts with inner brief.", specs: { inseam: "5 in" } },
  { id: "u4", slug: "ultragrip-court", name: "UltraGrip Court", price: 95, gender: "Women", category: "Shoes", colors: ["White","Mint"], sizes: [5,6,7,8,9,10], rating: 4.5, tags: ["new"], img: "https://picsum.photos/seed/court4/1200/900", images: ["https://picsum.photos/seed/court4/1200/900","https://picsum.photos/seed/court4b/1200/900"], description: "Stability and grip for quick direction changes.", specs: { court: "Hard" } },
  { id: "u5", slug: "originals-track-jacket", name: "Originals Track Jacket", price: 85, gender: "Unisex", category: "Apparel", colors: ["Black","Navy"], sizes: ["XS","S","M","L","XL"], rating: 4.8, tags: ["heritage"], img: "https://picsum.photos/seed/trackjacket5/1200/900", images: ["https://picsum.photos/seed/trackjacket5/1200/900"], description: "Retro track jacket with modern fleece comfort.", specs: { fit: "Regular" } },
  { id: "u6", slug: "boostlite-runner", name: "BoostLite Runner", price: 110, gender: "Unisex", category: "Shoes", colors: ["Core Black","Solar Red"], sizes: [6,7,8,9,10,11,12], rating: 4.3, tags: ["outlet"], img: "https://picsum.photos/seed/boostlite6/1200/900", images: ["https://picsum.photos/seed/boostlite6/1200/900"], description: "Cushioned ride in a lightweight package.", specs: { weight: "280 g" } },
  { id: "u7", slug: "team-duffel-45l", name: "Team Duffel 45L", price: 60, gender: "Unisex", category: "Accessories", colors: ["Black","Olive"], sizes: ["One Size"], rating: 4.6, tags: [], img: "https://picsum.photos/seed/duffel7/1200/900", images: ["https://picsum.photos/seed/duffel7/1200/900"], description: "Spacious duffel for gym or travel.", specs: { volume: "45 L" } },
  { id: "u8", slug: "club-hoodie-fleece", name: "Club Hoodie Fleece", price: 65, gender: "Unisex", category: "Apparel", colors: ["Heather Gray","Black"], sizes: ["XS","S","M","L","XL"], rating: 4.5, tags: ["bestseller"], img: "https://picsum.photos/seed/hoodie8/1200/900", images: ["https://picsum.photos/seed/hoodie8/1200/900"], description: "Soft fleece hoodie with kangaroo pocket.", specs: { material: "Cotton blend" } },
];

export const CATEGORIES = ["Shoes","Apparel","Accessories"];
export const GENDERS = ["Men","Women","Unisex"];
